"""Site configuration scaffolding utilities."""

from __future__ import annotations

import sys
from pathlib import Path
from urllib.parse import urlparse

import click


def _derive_include_pattern(url: str) -> str:
    """Derive an include pattern from a URL."""
    parsed = urlparse(url)
    base = f"{parsed.scheme}://{parsed.netloc}"
    path = parsed.path.rstrip("/")
    if path:
        return f"{base}{path}/**"
    return f"{base}/**"


def scaffold_site_config(
    site_name: str,
    sites_dir: Path,
    url: str | None = None,
    interactive: bool = True,
) -> Path:
    """
    Create a new site configuration file.

    Args:
        site_name: Site identifier (becomes filename).
        sites_dir: Directory to create config in.
        url: Optional starting URL.
        interactive: Whether to prompt for missing fields.

    Returns:
        Path to created config file.

    Raises:
        click.ClickException: If config already exists or required fields missing.
    """
    config_path = sites_dir / f"{site_name}.yaml"

    if config_path.exists():
        raise click.ClickException(f"Config already exists: {config_path}")

    # Get URL if not provided
    if not url and interactive:
        if sys.stdin.isatty():
            url = click.prompt("Entrypoint URL", type=str)
        else:
            raise click.ClickException("--url is required in non-interactive mode")

    if not url:
        raise click.ClickException("URL is required. Use --url or run interactively.")

    # Derive values from URL
    include_pattern = _derive_include_pattern(url)

    # Get site name if interactive
    display_name = site_name.replace("-", " ").title()
    if interactive and sys.stdin.isatty():
        display_name = click.prompt("Site name", default=display_name)

    # Get max pages if interactive
    max_pages = 100
    if interactive and sys.stdin.isatty():
        max_pages = click.prompt("Max pages", default=100, type=int)

    # Generate YAML content
    content = f"""# Site configuration for {display_name}
# Generated by: supacrawl init

name: {display_name}

entrypoints:
  - {url}

include:
  - {include_pattern}

exclude: []

max_pages: {max_pages}

formats:
  - markdown

only_main_content: true

include_subdomains: false
"""

    sites_dir.mkdir(parents=True, exist_ok=True)
    config_path.write_text(content, encoding="utf-8")

    return config_path

